import zipfile as zi
f=open('one.txt','w+')
f.write(' one ')
f.close()
a=open('two.txt','w+')
a.write(' two ')
a.close()
comp_file=zi.ZipFile('comp_file.zip','w')
comp_file.write('one.txt',compress_type=zi.ZIP_DEFLATED)
comp_file.write('two.txt',compress_type=zi.ZIP_DEFLATED)
comp_file.close()
zip_obj=zi.ZipFile('comp_file.zip','r')
zip_obj.extractall('extracted_content')